// qwik/src/components/SearchInput.jsx
import { component$ } from '@builder.io/qwik';

export default component$((props) => {
  return (
    <input
      class="input flex-grow flex-shrink-0 w-full inline-block"
      type="text"
      placeholder="Search"
      value={props.searchValue.value}
      onInput$={(event) => props.searchValue.value = event.target.value}
      data-testid="searchButton"
    />
  );
});

// solid/src/components/SearchInput.jsx
function SearchInput(props) {
  return (
    <input
      className="input flex-grow flex-shrink-0 w-full inline-block"
      type="text"
      placeholder="Search"
      value={props.searchValue}
      onInput={(event) => props.setSearchValue(event.target.value)}
      data-testid="searchButton"
    />
  );
}

export default SearchInput;
