// solid/src/components/CustomLink.jsx
import { createSignal, createEffect } from "solid-js";
import { A, useLocation } from "solid-start";

function CustomLink({ href, children, dataTestId, ...props }) {
  return (
    <A
      href={href}
      data-testid={dataTestId}
      {...props}
      className="block py-2 pr-4 hover:scale-110 text-gray-700"
    >
      {children}
    </A>
  );
}

export default CustomLink;

// next-app/components/CustomLink.jsx
import React from 'react';
import Link from 'next/link';

function CustomLink({ href, children, dataTestId, ...props }) {
  return (
    <Link
      href={href}
      data-testid={dataTestId}
      {...props}
      className='block py-2 pr-4 hover:scale-110 text-gray-700'
    >
      {children}
    </Link>
  );
}

export default CustomLink;
