// react-client/src/context/CartContext.jsx
import React, { createContext, useState } from 'react';

export const CartContext = createContext(null);

const CartContextProvider = (props) => {
  const [cartProducts, setCartProducts] = useState([]);

  function getTotalQuantity() {
    let totalQuantity = 0;

    cartProducts.forEach(product => totalQuantity += product.quantity);

    return totalQuantity;
  }

  function getTotalPrice() {
    let totalPrice = 0;
    cartProducts.forEach(cartProduct => {
      totalPrice += (cartProduct.price * cartProduct.quantity);
    });
    return totalPrice;
  }

  function getProductQuantity(productId) {
    const quantity = cartProducts.find(product => product.id === productId)?.quantity;

    if (quantity === undefined) {
      return 0;
    }

    return quantity;
  }

  function addToCart(newProduct) {
    const quantity = getProductQuantity(newProduct.id);

    if (quantity === 0) {
      setCartProducts(
        [
          ...cartProducts,
          {
            ...newProduct,
            quantity: 1
          }
        ]
      );
    } else {
      setCartProducts(
        cartProducts.map(
          product =>
            product.id === newProduct.id
              ? { ...product, quantity: product.quantity + 1 }
              : product
        )
      );
    }
  }

  function removeFromCart(productId) {
    const quantity = getProductQuantity(productId);

    if(quantity === 0) {
      return;
    }
    else if(quantity === 1) {
      deleteFromCart(productId);
    } else {
      const newProducts = cartProducts.map(
        product =>
          product.id === productId
            ? { ...product, quantity: product.quantity - 1 }
            : product
      );
      setCartProducts(newProducts);
    }
  }

  function deleteFromCart(id) {
    setCartProducts(
      cartProducts =>
        cartProducts.filter(product => {
          return product.id !== id;
        })
    );
  }

  const checkout = () => {
    setCartProducts([]);
  };

  const contextValue = {
    cartProducts,
    getTotalQuantity,
    getTotalPrice,
    getProductQuantity,
    addToCart,
    removeFromCart,
    checkout,
  };

  return (
    <CartContext.Provider value={contextValue}>
      {props.children}
    </CartContext.Provider>
  );
};

export default CartContextProvider;

// qwik/src/context/CartContext.jsx
import {
  createContextId,
} from '@builder.io/qwik';

const CartContext = createContextId('cart');
export default CartContext;

export function getTotalQuantity(cartProducts) {
  let totalQuantity = 0;

  cartProducts.value.forEach(product => totalQuantity += product.quantity);

  return totalQuantity;
}

export function getProductQuantity(productId, cartProducts) {
  const quantity = cartProducts.value.find(product => product.id === productId)?.quantity;

  if (quantity === undefined) {
    return 0;
  }

  return quantity;
}

export function addToCart(newProduct, cartProducts) {
  const quantity = getProductQuantity(newProduct.id, cartProducts);

  if (quantity === 0) {
    cartProducts.value = [
      ...cartProducts.value,
      {
        ...newProduct,
        quantity: 1
      }
    ];
  } else {
    cartProducts.value = cartProducts.value.map(product =>
      product.id === newProduct.id
        ? { ...product, quantity: product.quantity + 1 }
        : product
    );
  }
}

export function removeFromCart(productId, cartProducts) {
  const quantity = getProductQuantity(productId, cartProducts);

  if(quantity === 0) {
    return;
  }
  else if(quantity === 1) {
    deleteFromCart(productId, cartProducts);
  } else {
    const newProducts = cartProducts.value.map(
      product =>
        product.id === productId
          ? { ...product, quantity: product.quantity - 1 }
          : product
    );
    cartProducts.value = newProducts;
  }
}

function deleteFromCart(id, cartProducts) {
  cartProducts.value = cartProducts.value.filter(product => product.id !== id);
}
