// qwik/src/routes/products/index.jsx
import { component$, useResource$, Resource } from '@builder.io/qwik';
import ProductList from '~/components/ProductList';

export default component$(() => {
  const products = useResource$(async () => {
    const response = await fetch(
      'http://localhost:8080/api/products/'
    );
    const data = await response.json();
    return data;
  });

  return (
    <Resource
      value={products}
      onPending={() => <div>loading...</div>}
      onResolved={products => (
        <ProductList products={products}/>
      )}
    />
  );
});

// react/src/pages/Products.jsx
import React, { useState, useEffect } from 'react';
import ProductList from '../components/ProductList';

function Products() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    async function getProducts() {
      const response = await fetch('http://localhost:8080/api/products/');
      const products = await response.json();
      setProducts(products);
    }

    getProducts();
  }, []);


  return (
    <>
      <ProductList
        products={products}
      />
    </>
  );
}

export default Products;
