// qwik/src/routes/orders/[id]/index.jsx
/* eslint-disable qwik/loader-location */
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';
import OrderProductCard from '~/components/OrderProductCard';

export const useOrderDetails = routeLoader$(async (requestEvent) => {
  const response = await fetch(`http://${import.meta.env.VITE_SERVER_HOST_NAME}:8080/api/orders/${requestEvent.params.id}`);
  const order = await response.json();
  return order;
});

export default component$(() => {
  const order = useOrderDetails();

  const getDatetimeString = (createdAt) => {
    const datetime = new Date(createdAt);
    const options = { hour: 'numeric', minute: 'numeric' };
    return `${datetime.toLocaleDateString('fi-FI')} ${datetime.toLocaleTimeString('en-GB', options)}`;
  };

  return (
    <>
      <h1 class='text-center'>Order on {getDatetimeString(order.value.createdAt)}</h1>
      <div class='m-4 text-center xs:text-start'>
        <p>Recipient name: {order.value.recipientInfo.firstName} {order.value.recipientInfo.lastName}</p>
        <p>Delivery address: {order.value.recipientInfo.address}</p>
        <p>Total price: {order.value.totalPrice}€</p>
      </div>
      <h2 class='m-4 text-center xs:text-start'>Products</h2>
      <div class='xs:grid xs:grid-cols-2 sm:block'>
        {order.value.products.map(productObject =>
          <div key={productObject.product.id} class='mx-2'>
            <OrderProductCard product={productObject.product} quantity={productObject.quantity} />
          </div>
        )}
      </div>
    </>
  );
});

// next-react/app/orders/[id]/page.jsx
import React from 'react';
import OrderProductCard from '@/components/OrderProductCard';

async function getOrder(id) {
  const response = await fetch(
    // eslint-disable-next-line no-undef
    `http://${process.env.SERVER_HOST_NAME}:8080/api/orders/${id}`,
    {
      next: { revalidate: 10 },
    },
  );
  const data = await response.json();

  return data;
}

async function Order({ params }) {
  const order = await getOrder(params.id);

  const getDatetimeString = (createdAt) => {
    const datetime = new Date(createdAt);
    const options = { hour: 'numeric', minute: 'numeric' };
    return `${datetime.toLocaleDateString('fi-FI')} ${datetime.toLocaleTimeString('en-GB', options)}`;
  };

  return (
    <>
      <h1 className='text-center'>Order on {getDatetimeString(order.createdAt)}</h1>
      <div className='m-4 text-center xs:text-start'>
        <p>Recipient name: {order.recipientInfo.firstName} {order.recipientInfo.lastName}</p>
        <p>Delivery address: {order.recipientInfo.address}</p>
        <p>Total price: {order.totalPrice}€</p>
      </div>
      <h2 className='m-4 text-center xs:text-start'>Products</h2>
      <div className='xs:grid sm:block xs:grid-cols-2'>
        {
          order.products.map(productObject =>
            <div key={productObject.product.id} className='mx-2'>
              <OrderProductCard product={productObject.product} quantity={productObject.quantity} />
            </div>
          )
        }
      </div>
    </>
  );
}

export default Order;
