// solid/src/routes/products/index.jsx
import { createResource } from "solid-js";
import ProductList from '../../components/ProductList';

async function fetchProducts() {
  const response = await fetch(`http://${import.meta.env.VITE_SERVER_HOST_NAME}:8080/api/products/`);
  const data = await response.json();
  return data;
}

function Products() {
  const [products] = createResource(fetchProducts);

  return (
    <Show
      when={products()}
      fallback={<div>Loading...</div>}
    >
      <ProductList
        products={products()}
      />
    </Show>
  );
}

export default Products;

// qwik/src/routes/products/index.jsx
import { component$, useResource$, Resource } from '@builder.io/qwik';
import { isBrowser } from '@builder.io/qwik/build';
import ProductList from '~/components/ProductList';

export default component$(() => {
  const products = useResource$(async () => {
    const response = isBrowser ?
      await fetch('http://localhost:8080/api/products/') :
      await fetch(`http://${import.meta.env.VITE_SERVER_HOST_NAME}:8080/api/products/`);
    const data = await response.json();
    return data;
  });

  return (
    <Resource
      value={products}
      onPending={() => <div>loading...</div>}
      onResolved={products => (
        <ProductList products={products}/>
      )}
    />
  );
});
