// react-opt-client/src/pages/Cart.jsx
import React, { useContext } from 'react';
import { CartContext } from '../context/CartContext';
import OrderForm from '../components/OrderForm';
import CartProductCard from '../components/CartProductCard';

function Cart() {
  const {
    cartProducts,
    getProductQuantity,
    addToCart,
    removeFromCart,
    getTotalPrice,
  } = useContext(CartContext);

  const totalPrice = getTotalPrice();

  return (
    <>
      <div className='xs:grid sm:block xs:grid-cols-2'>
        {cartProducts.map(product =>
          <div key={product.id}  className='m-2 flex justify-between items-center'>
            <CartProductCard
              product={product}
              removeFromCart={() => removeFromCart(product.id)}
              addToCart={() => addToCart(product)}
              count={getProductQuantity(product.id)}
            />
          </div>
        )}
      </div>
      { cartProducts.length > 0
        ?
        <>
          <strong className='mx-2 xs:text-left text-center font-bold'>Total price: {totalPrice}€</strong>
          <OrderForm />
        </>
        :
        <p>Shopping cart is empty</p>
      }
    </>
  );
}

export default Cart;

// qwik/src/routes/cart/index.jsx
import { component$, useContext, $ } from '@builder.io/qwik';
import CartContext, { addToCart, removeFromCart, getProductQuantity, getTotalPrice } from '~/context/CartContext';
import CartProductCard from '~/components/CartProductCard';
import OrderForm from '~/components/OrderForm';

export default component$(() => {
  const cartProducts = useContext(CartContext);
  const totalPrice = getTotalPrice(cartProducts);

  return (
    <>
      <div class='xs:grid sm:block xs:grid-cols-2'>
        {cartProducts.value.map(product =>
          <div key={product.id}  class='m-2 flex justify-between items-center'>
            <CartProductCard
              product={product}
              removeFromCart={$(() => removeFromCart(product.id, cartProducts))}
              addToCart={$(() => addToCart(product, cartProducts))}
              count={getProductQuantity(product.id, cartProducts)}
            />
          </div>
        )}
      </div>
      { cartProducts.value.length > 0
        ?
        <>
          <strong class='mx-2 xs:text-left text-center font-bold'>Total price: {totalPrice}€</strong>
          <OrderForm />
        </>
        :
        <p class='mx-2'>Shopping cart is empty</p>
      }
    </>
  );
});
