// qwik/src/routes/products/index.jsx
import { component$, useResource$, Resource } from '@builder.io/qwik';
import ProductList from '~/components/ProductList';

export default component$(() => {
  const products = useResource$(async () => {
    const response = await fetch(
      'http://localhost:8080/api/products/'
    );
    const data = await response.json();
    return data;
  });

  return (
    <Resource
      value={products}
      onPending={() => <div>loading...</div>}
      onResolved={products => (
        <ProductList products={products}/>
      )}
    />
  );
});

// react-client/src/pages/Products.jsx
import React, { useState, useEffect } from 'react';
import ProductList from '../components/ProductList';

function Products() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    async function fetchData() {
      const response = await fetch('http://localhost:3001/api/products');
      const data = await response.json();
      setProducts(data);
    }
    fetchData();
  }, []);

  return (
    <>
      <h1>Products</h1>
      <ProductList products={products} />
    </>
  );
}

export default Products;
