// preact-opt/src/components/AddToCartButton.jsx
import React, { useContext } from 'react';
import classNames from 'classnames';
import { CartContext } from '../context/CartContext';

export default function AddToCartButton(props) {
  const { addToCart, removeFromCart, getProductQuantity } = useContext(CartContext);
  return (
    <div className='inline-flex justify-center'>
      {getProductQuantity(props.product.id) > 0
        ?
        <div className='inline'>
          <button
            className='btn w-10 inline-flex justify-center btn-red'
            onClick={ (e) => {
              e.preventDefault();
              removeFromCart(props.product.id);
            }}
            data-testid="leftButton"
          >
            -
          </button>
          <div className={classNames('inline-flex w-12 justify-center', props.textClassNames)}>{getProductQuantity(props.product.id)}</div>
          <button
            className='btn w-10 inline-flex justify-center btn-blue'
            onClick={ (e) => {
              e.preventDefault();
              addToCart(props.product);
            }}
            data-testid="rightButton"
          >
            +
          </button>
        </div>
        :
        <button data-testid="addToCartButton" onClick={() => addToCart(props.product)} className='btn btn-blue block w-32'>Add to cart</button>
      }
    </div>
  );
}

// qwik/src/components/AddToCartButton.jsx
import { component$, useContext, $ } from '@builder.io/qwik';
import CartContext, { addToCart, removeFromCart, getProductQuantity } from '~/context/CartContext';
import classNames from 'classnames';

export default component$((props) => {
  const cartProducts = useContext(CartContext);

  return (
    <div class='inline-flex justify-center'>
      {getProductQuantity(props.product.id, cartProducts) > 0
        ?
        <div class='inline'>
          <button
            class='btn w-10 inline-flex justify-center btn-red'
            preventdefault:click 
            onClick$={() => removeFromCart(props.product.id, cartProducts)}
            data-testid="leftButton"
          >
            -
          </button>
          <div class={classNames('inline-flex w-12 justify-center', props.textClassNames)}>{getProductQuantity(props.product.id, cartProducts)}</div>
          <button
            class='btn w-10 inline-flex justify-center btn-blue'
            preventdefault:click 
            onClick$={() => addToCart(props.product, cartProducts)}
            data-testid="rightButton"
          >
            +
          </button>
        </div>
        :
        <button data-testid="addToCartButton" onClick$={() => addToCart(props.product, cartProducts)} class='btn btn-blue block w-32'>Add to cart</button>
      }
    </div>
  );
});
