// astro-preact/src/components/CustomLink.jsx
import React from 'react';
import classNames from 'classnames';

function CustomLink({ href, children, dataTestId, ...props }) {
  return (
    <a
      href={href}
      data-testid={dataTestId}
      {...props}
      className={classNames('block py-2 pr-4 hover:scale-110 text-gray-700')}
    >
      {children}
    </a>
  );
}

export default CustomLink;

// qwik/src/components/CustomLink.jsx
import { Slot, component$ } from '@builder.io/qwik';
import classNames from 'classnames';

export default component$(({ href, dataTestId }) => {
  return (
    <a
      href={href}
      data-testid={dataTestId}
      class={classNames('block py-2 pr-4 hover:scale-110 text-gray-700')}
    >
      <Slot />
    </a>
  );
});
