// qwik/src/root.jsx
import { component$, useContextProvider, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';
import { RouterHead } from './components/router-head/router-head';

import CartContext from './context/CartContext';

import './global.css';

export default component$(() => {
  /**
   * The root of a QwikCity site always start with the <QwikCityProvider> component,
   * immediately followed by the document's <head> and <body>.
   *
   * Dont remove the `<head>` and `<body>` elements.
   */

  const cartProducts = useSignal([]);

  useVisibleTask$(() => {
    if (localStorage.getItem('cart')) {
      cartProducts.value = JSON.parse(localStorage.getItem('cart'));
    } else {
      localStorage.setItem('cart', JSON.stringify(cartProducts));
    }
  });

  useContextProvider(
    CartContext,
    useSignal([])
  );

  return (
    <QwikCityProvider>
      <head>
        <meta charSet="utf-8" />
        <link rel="manifest" href="/manifest.json" />
        <RouterHead />
      </head>
      <body lang="en" class="bg-slate-200">
        <RouterOutlet />
        <ServiceWorkerRegister />
      </body>
    </QwikCityProvider>
  );
});

// solid/src/root.jsx
// @refresh reload
import { Suspense } from "solid-js";
import { isServer } from "solid-js/web";
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
} from "solid-start";

import NavBar from "./components/NavBar";
import { CartContextProvider } from "./context/CartContext";

import "./root.css";
export default function Root() {
  if (!isServer && !localStorage.getItem('cart')) {
    localStorage.setItem('cart', JSON.stringify([]));
  }

  return (
    <Html lang="en">
      <Head>
        <Title>Solid</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Body className="bg-slate-200">
        <Suspense>
          <CartContextProvider value={!isServer ? JSON.parse(localStorage.getItem('cart')) : []}>
            <NavBar />
            <ErrorBoundary>
                <div className='mx-auto max-w-xl w-full my-2'>
                  <div className='mx-2'>
                    <Routes>
                      <FileRoutes />
                    </Routes>
                  </div>
                </div>
            </ErrorBoundary>
          </CartContextProvider>
        </Suspense>
        <Scripts />
      </Body>
    </Html>
  );
}
